# Generated by Django 5.1.1 on 2024-09-05 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('startup_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.TextField()),
                ('incorporation_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Ideation', 'Ideation'), ('Seed Stage', 'Seed Stage'), ('Growth', 'Growth'), ('Established', 'Established')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=45)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_summary', models.TextField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipants',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('Coordinator', 'Coordinator'), ('Host', 'Host'), ('Guests/Participants', 'Guests/Participants')], max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='IPR',
            fields=[
                ('ipr_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('ipr_type', models.CharField(choices=[('Patent', 'Patent'), ('Trademark', 'Trademark'), ('Copyright', 'Copyright')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('application_number', models.CharField(blank=True, max_length=20, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=20, null=True)),
                ('file_date', models.DateField(blank=True, null=True)),
                ('granted_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Filed', 'Filed'), ('Granted', 'Granted'), ('In-process', 'In-process'), ('Rejected', 'Rejected')], max_length=20)),
                ('document_link', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Mentorship',
            fields=[
                ('mentorship_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Terminated', 'Terminated')], max_length=20)),
                ('mentee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentees', to='user.user')),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentors', to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('research_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('related_publication', models.TextField(blank=True, null=True)),
                ('lead_researcher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
                ('related_patent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.ipr')),
            ],
        ),
        migrations.CreateModel(
            name='Innovation',
            fields=[
                ('innovation_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Concept', 'Concept'), ('Prototype', 'Prototype'), ('Development', 'Development'), ('Deployed', 'Deployed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_ipr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.ipr')),
                ('related_research', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.research')),
                ('associated_startup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.startup')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('request_title', models.CharField(max_length=100)),
                ('request_type', models.CharField(choices=[('Funding', 'Funding'), ('Mentorship', 'Mentorship'), ('Collaboration', 'Collaboration'), ('Consultation', 'Consultation'), ('Investment', 'Investment'), ('Advisor', 'Advisor'), ('Other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('In Process', 'In Process'), ('Completed', 'Completed'), ('Requested', 'Requested'), ('Accepted', 'Accepted')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.innovation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('startup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.startup')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('investment_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('investment_type', models.CharField(choices=[('Startup', 'Startup'), ('Innovation', 'Innovation')], max_length=20)),
                ('round', models.CharField(choices=[('Seed', 'Seed'), ('Series 1', 'Series 1'), ('Series 2', 'Series 2'), ('Series 3', 'Series 3'), ('IPO', 'IPO')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField(blank=True, null=True)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='user.user')),
                ('innovation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.innovation')),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investor', to='user.user')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.startup')),
            ],
        ),
    ]
