# Generated by Django 5.1.1 on 2024-09-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_startup_event_eventparticipants_ipr_mentorship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Researcher'), (1, 'Entrepreneur'), (2, 'Mentor'), (3, 'Advisor'), (4, 'Investor'), (5, 'Funding Agency'), (6, 'Government official'), (7, 'Legal Advisor')]),
        ),
    ]
